version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/frontend/backend"
    schedule:
      interval: "weekly"
    groups:
      frontend-backend:
        patterns:
        - "*"
  - package-ecosystem: "npm"
    directories:
      - "/backend"
    schedule:
      interval: "weekly"
    groups:
      bakend:
        patterns:
        - "*"
