version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/frontend/backend"
      - "/backend"
    schedule:
      interval: "weekly"
    groups:
      backend:
        patterns:
        - "*"
  - package-ecosystem: "npm"
    directories:
      - "/frontend"
      - "/backend/frontend"
    schedule:
      interval: "weekly"
    groups:
      frontend:
        patterns:
        - "jquery*"
        - "fast-jwt*"
  - package-ecosystem: "npm"
    directories:
      - "/backend"
      - "/backend/frontend"
      - "/doesnt-exist"
    schedule:
      interval: "weekly"
    groups:
      frontend:
        patterns:
        - "jquery*"
